services :
   - type : web
     name : autofilterbot
     runtime : go
     repo : https://github.com/Jisin0/autofilterbot.git
     buildCommand: go build .
     startCommand: ./autofilterbot
     envVars :
       - key : BOT_TOKEN
         value : your-bots-token
       - key: MONGODB_URI
         value : mongodb-cluster-uri
       - key : ADMINS
         value: bot-admin-ids
       - key : FILE_CHANNELS
         value: file-channel-ids
       - key : PORT
         value : 10000